"""C/Python COBS parity: the bridge firmware's cobs.h vs cambium.wire.cobs.

Compiles firmware/cambium_bridge/test_cobs_host.c on the host (plain cc) and
runs it against the shared golden vectors. The C harness stays JSON-free: this
test generates a C array header from tests/golden/cobs_vectors.json into a
temp dir first. Python's own conformance to the same vectors is test_cobs.py;
the direct cross-check here closes the loop.
"""

import json
import shutil
import subprocess
from pathlib import Path

import pytest

from cambium.wire.cobs import cobs_encode, crc16_ccitt

ROOT = Path(__file__).resolve().parent.parent
GOLDEN = ROOT / "tests" / "golden" / "cobs_vectors.json"
FW_DIR = ROOT / "firmware" / "cambium_bridge"
CC = shutil.which("cc")

VECTORS = json.loads(GOLDEN.read_text())["vectors"]


def _c_bytes(name: str, data: bytes) -> str:
    # C forbids empty initializer lists (pre-C23), so a zero-length vector
    # gets a 1-byte dummy array; its length constant is still 0.
    body = ", ".join(f"0x{b:02x}" for b in data) if data else "0x00"
    return f"static const uint8_t {name}[] = {{{body}}};\n"


def _generate_header(vectors: list[dict]) -> str:
    out = [
        "/* generated by tests/test_c_cobs_parity.py from cobs_vectors.json */\n",
        "#include <stdint.h>\n",
        "typedef struct {\n",
        "  const char *name;\n",
        "  const uint8_t *decoded; unsigned decoded_len;\n",
        "  const uint8_t *encoded; unsigned encoded_len;\n",
        "  uint16_t crc16;\n",
        "} cobs_vec_t;\n",
    ]
    for i, v in enumerate(vectors):
        out.append(_c_bytes(f"v{i}_dec", bytes.fromhex(v["decoded"])))
        out.append(_c_bytes(f"v{i}_enc", bytes.fromhex(v["encoded"])))
    out.append("static const cobs_vec_t cobs_vectors[] = {\n")
    for i, v in enumerate(vectors):
        dec_len = len(bytes.fromhex(v["decoded"]))
        enc_len = len(bytes.fromhex(v["encoded"]))
        out.append(
            f'  {{"{v["name"]}", v{i}_dec, {dec_len}, v{i}_enc, {enc_len}, '
            f'{v["crc16_ccitt"]}}},\n'
        )
    out.append("};\n")
    out.append(f"static const unsigned cobs_vector_count = {len(vectors)};\n")
    return "".join(out)


def test_python_matches_goldens():
    # Belt-and-braces: if the vectors file itself drifted from cobs.py, fail
    # HERE rather than blaming the C side.
    for v in VECTORS:
        decoded = bytes.fromhex(v["decoded"])
        assert cobs_encode(decoded).hex() == v["encoded"], v["name"]
        assert crc16_ccitt(decoded) == v["crc16_ccitt"], v["name"]


@pytest.mark.skipif(CC is None, reason="no host C compiler (cc) on PATH")
def test_c_agrees_with_python(tmp_path):
    (tmp_path / "cobs_vectors_gen.h").write_text(_generate_header(VECTORS))
    exe = tmp_path / "test_cobs_host"
    subprocess.run(
        [
            CC, "-std=c99", "-Wall", "-Wextra", "-Werror",
            "-I", str(tmp_path), "-I", str(FW_DIR),
            str(FW_DIR / "test_cobs_host.c"),
            "-o", str(exe),
        ],
        check=True,
    )
    res = subprocess.run([str(exe)], capture_output=True, text=True)
    assert res.returncode == 0, f"C parity harness failed:\n{res.stdout}{res.stderr}"
